@extends('errors.layout')
@section('title', 'Page Expired')
@section('subtitle', "Your session has expired.")
@section('message', "Please refresh the page or try again. Your session may have timed out due to inactivity.")
@section('code', 419)
