@extends('errors.layout')
@section('title', 'Service Unavailable')
@section('subtitle', "We're experiencing technical difficulties.")
@section('message', "Our team is working to resolve the issue. Please try again later.")
@section('code', 503)
